#: HTTP OK
STATUS_OK = 200

#: HTTP BAD REQUEST
STATUS_BAD_REQUEST = 400

#: HTTP CONFLICT
STATUS_CONFLICT = 409

#: HTTP INTERNAL SERVER ERROR
STATUS_INTERNAL_SERVER_ERROR = 500

#: MIMETYPE JSON
MIMETYPE_JSON = 'application/json'
