-- Role: metadatahub
-- DROP ROLE metadatahub;

CREATE ROLE metadatahub WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION
  ENCRYPTED PASSWORD 'md5da2c67202e408de532411c0cd0fb0b21';
